### PR TITLE
Disable padded-blocks rule due to meaningless

### PR DESCRIPTION
**Pull request by kossnocorp**
Before, this example will cause error (because of empty line before `else`):

``` js
if (this.props.active) {
  icon = 'play'
  label = 'You are working'

} else {
  icon = 'pause'
  label = 'You are not working'
}
```

### CODE REVIEW

**Comment by falsefalse** [comment]
:+1:

**Comment by chrome** [comment]
:-1: 
`} else {` works well for dividing logic block visually, this empty line doesn't make any sense

**Comment by mdumic** [comment]
:+1:

**Comment by edtsech** [comment]
:-1: Agree with @chrome

**Comment by nkabardin** [comment]
:-1:

**Comment by lest** [comment]
:-1:

**Comment by falsefalse** [comment]
@chrome 
> If "never" then all blocks should never start or end with a blank line.
`} else {` will work as it used to.

**Comment by kossnocorp** [comment]
3/4

**Pull request closed without merging**
